sudo: required
services:
  - docker

before_install:
  - docker build -t ccccc170/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ccccc170?react-test npm test -- --coverage

after_success:
  - docker build -t ccccc170/multi-client ./client
  - docker build -t ccccc170/multi-nginx ./nginx
  - docker build -t ccccc170/multi-server ./server
  - docker build -t ccccc170/multi-worker ./worker